<?php
$methods = array();

include __DIR__ . '/../events/WhatsAppEventListener.php';
$refl = new ReflectionClass('WhatsAppEventListener');


/** @var $method ReflectionMethod */
foreach ($refl->getMethods() as $method) {
    $methodBody = '    function ' . $method->getName() . '(';
    /** @var $param ReflectionParameter */
    $parameters = array();
    foreach ($method->getParameters() as $param) {
        $parameters[] = $param->getName();

    }
    $methodBody .= '$' . implode(', $', $parameters);
    $methodBody .= ")\n    {\n        ";
    $methodBody .= '$this->outputEvent(__FUNCTION__, compact(';
    $methodBody .= "'" . implode('\', \'', $parameters) . "'";
    $methodBody .= '));';
    $methodBody .= "\n    }";
    $methods[] = $methodBody;
    unset($methodBody);
}

$methods = implode("\n\n", $methods);

$file = <<<PHP
<?php
/**
 * This class is generated by running the generateEventListener.php in this directory
 */
class WhatsAppDaemonEventListener extends AbstractWhatsAppDaemonEventListener
{
{$methods}
}
PHP;

file_put_contents(__DIR__ . '/WhatsAppDaemonEventListener.php', $file);